#example parameters for our SNV analysis, determined by Drayton Harvey from paper {ADD CITATION} in accordance with GATK best practices.

# Main working directory, sample directory and suffix of reads
workDir: /path/to/working/directory
readsDir: /path/to/reads/directoru
read1Suffix: _1.fastq.gz
read2Suffix: _2.fastq.gz
probandsuff: _P
fathersuff: _F
mothersuff: _M


#BWAFastqtoSAM parameters, same reference for MergeBamAlignment
reference: '/path/to/reference/file'
nThreads: 16
reference_bowtie: '/path/to/reference/file/bowtie2'

#MergeBamAlignment parameters
SortOrder: 'unsorted'
ClipAdapters: false
AddMateCigar: true
MaxInsertsOrDels: -1
PrimaryAlign: 'MostDistant'
UnmapCont: false
AttrRet1: 'XS'
AttrRet2: 'XA'

# trim_galore parameters
minPhred: 20
minOverlap: 3

#AddRGtoBam
RGID: #Read-Group ID
RGLB: #Read-Group library
RGPL: #Read-Group platform (e.g. ILLUMINA, SOLID)
RGPU: #Read-Group platform unit (eg. run barcode)
RGSM: #Read-Group sample name

#BaseRecalibrate
KnownSites: '/path/to/knownsites/reference'
JavaOptions: 'Xmx4g'

#VariantRecalibrator
hapmap: '/path/to/hapmap/file'
omni: '/path/to/omni/file'
1000G: '/path/to/1000/genome/file'
dbsnp: '/project/rsubrama_477/riya/VariantCalling/reference/gatk/Homo_sapiens_assembly38.dbsnp138.vcf'

#family ped
ped: 'path/to/.ped/file/'

#config for snpEff download from snpEff installation website
snpEffconfig: '/path/to/SnpEff/config/file'
